/**
 * Created by charlie on 6/9/17.
 */

module.exports = {
  website: 'website',
  phone: 'phone',
  email: 'email',
  food: 'Foods',
  coffee: 'Coffee',
  pub: 'Pub',
  log_in_with_facebook_button_title: "Login with Facebook",
  empty_promotion_list: 'This list is empty!',
  account_login_error: 'Problem occurred during login.',
  account_details_navigate_to_my_added_places_title: 'My created places',
  account_details_my_added_places: 'My created places',
  account_details_my_favorite_places: 'My favorites',
  account_details_navigate_to_my_coffee: 'Coffee',
  account_details_navigate_to_my_pub: 'Pub',
  account_details_navigate_to_my_food: 'Food',
  account_details_log_out_button_title: 'Logout',
  comment_context_menu_title: 'Action',
  comment_context_menu_question: 'What do you want to do?',
  comment_context_menu_button_delete: 'Delete',
  comment_context_menu_button_edit: 'Edit',
  comment_component_default_title: 'Comments',
  comment_input_box_hint: 'Write something here...',
  comment_list_item_save_button: 'Save',
  comment_list_item_cancel_button: 'Cancel',
  images_gallery_waiting: 'Loading ...',
  more_details_input_box_title_categories_list: 'Categories',
  more_details_input_box_title_input_name: 'Place Name',
  more_details_input_box_title_input_description: 'Description',
  more_details_input_box_title_input_address: 'Address',
  more_details_input_box_title_input_email: 'Email (OPTIONAL)',
  more_details_input_box_title_input_website: 'Website (OPTIONAL)',
  more_details_input_box_title_input_phone_number: 'Phone (OPTIONAL)',
  more_details_input_box_hint_input_name: 'e.g.: Highlands, Starbucks, ...',
  more_details_input_box_hint_input_description: 'Menu, workhours, prices, ...',
  more_details_input_box_hint_input_address: 'Press the next button to select',
  more_details_input_box_hint_input_email: 'example@gmail.com',
  more_details_input_box_hint_input_website: 'http://www.example.com/',
  more_details_input_box_hint_input_phone_number: '+84 222 3333 4444',
  more_details_save_changes_button: 'SAVE CHANGES',
  more_details_add_new_place_button: 'ADD THIS PLACE',
  more_details_delete_place_button: 'DELETE THIS PLACE',
  more_details_delete_image_alert_title: 'Delete Image',
  more_details_delete_image_alert_message: 'Do you want to delete this image?',
  more_details_delete_image_alert_yes_button: 'Yes',
  more_details_delete_image_alert_no_button: 'No',
  more_details_no_images_uploaded: 'Cannot select these images. Please try again',
  more_details_images_sources_title: 'Images Sources',
  more_details_images_sources_message: 'Where do you want to select the photos?',
  more_details_images_from_camera: 'Camera',
  more_details_images_from_sdcard: 'Sdcard',
  more_details_prompt_login_save_changes: 'Please login before using this feature',
  more_details_prompt_login_add_new_place: 'Please login before using this feature',
  more_details_images_are_loading: 'Please wait for finishing uploading images',
  more_details_at_least_one_image_added: 'At least one image must be added',
  more_details_input_error_detected: 'Some information is wrong',
  more_details_no_images_selected: 'Cannot select these images',
  more_details_delete_place_confirm_title: 'Confirm',
  more_details_delete_place_confirm_message: 'Do you want to delete this place?',
  more_details_delete_place_error_message: 'Cannot delete this place',
  more_details_delete_place_alert_yes_button: 'Yes',
  more_details_delete_place_alert_no_button: 'No',
  my_added_places_edit_place_title: 'Edit information',
  my_added_places_place_details_title: 'Place Details',
  my_added_places_not_log_in_message: 'You have not logged in',
  my_added_places_prompt_log_in: 'Please login before using this feature',
  place_details_report_error_title: 'Report',
  place_details_report_error_content: 'Let us know if anything is wrong',
  place_details_unable_open_map_message: 'Cannot open the map app',
  places_list_navigate_to_add_place_title: 'Add new place',
  places_list_search_bar_place_holder: 'Enter something to search',
  input_validation_util_name: 'Name',
  input_validation_util_description: 'Description',
};
