/**
 * Created by charlie on 6/9/17.
 */

module.exports = {
  website: 'trang web',
  phone: 'số điện thoại',
  email: 'hộp thư điện tử',
  food: 'Quán ăn',
  coffee: 'Quán cà phê',
  pub: 'Quán nhậu',
  log_in_with_facebook_button_title: "Đăng nhập qua Facebook",
  empty_promotion_list: 'Danh sách trống!',
  account_login_error: 'Lỗi xảy ra khi đăng nhập',
  account_details_navigate_to_my_added_places_title: 'Những nơi tôi đã thêm',
  account_details_my_added_places: 'Những nơi tôi đã thêm',
  account_details_my_favorite_places: 'Những nơi ưa thích',
  account_details_navigate_to_my_coffee: 'Quán cà phê',
  account_details_navigate_to_my_pub: 'Quán nhậu',
  account_details_navigate_to_my_food: 'Quán ăn',
  account_details_log_out_button_title: 'Đăng Xuât',
  comment_context_menu_title: 'Măm măm 24h',
  comment_context_menu_question: 'Bạn muốn làm gì với bình luận này?',
  comment_context_menu_button_delete: 'Xóa',
  comment_context_menu_button_edit: 'Chỉnh Sửa',
  comment_component_default_title: 'Bình luận',
  comment_input_box_hint: 'Nhập bình luận vào đây...',
  comment_list_item_save_button: 'Lưu',
  comment_list_item_cancel_button: 'Hủy',
  images_gallery_waiting: 'Đang tải...',
  more_details_input_box_title_categories_list: 'loại quán',
  more_details_input_box_title_input_name: 'Tên quán',
  more_details_input_box_title_input_description: 'Mô tả về quán',
  more_details_input_box_title_input_address: 'Địa chỉ quán',
  more_details_input_box_title_input_email: 'Email (tùy chọn)',
  more_details_input_box_title_input_website: 'Trang chủ (tùy chọn)',
  more_details_input_box_title_input_phone_number: 'Số điện thoại (tùy chọn)',
  more_details_input_box_hint_input_name: 'Ví dụ: quán cô ba, cà phê Highlands, ...',
  more_details_input_box_hint_input_description: 'Có món gì, giá cả, giờ mở cửa, ...',
  more_details_input_box_hint_input_address: 'Nhấn vào nút bên cạnh để chọn',
  more_details_input_box_hint_input_email: 'vidu@gmail.com',
  more_details_input_box_hint_input_website: 'http://www.vidu.com/',
  more_details_input_box_hint_input_phone_number: '+84 222 3333 4444',
  more_details_save_changes_button: 'LƯU CÁC THAY ĐỔI',
  more_details_add_new_place_button: 'THÊM NƠI NÀY',
  more_details_delete_place_button: 'XÓA BỎ NƠI NÀY',
  more_details_delete_image_alert_title: 'Măm măm 24h',
  more_details_delete_image_alert_message: 'Bạn có muốn xóa ảnh này?',
  more_details_delete_image_alert_yes_button: 'Có',
  more_details_delete_image_alert_no_button: 'Không',
  more_details_no_images_uploaded: 'Không thể chọn những ảnh này\nXin thực hiện lại',
  more_details_images_sources_title: 'Thêm ảnh',
  more_details_images_sources_message: 'Bạn muốn thêm ảnh từ đâu?',
  more_details_images_from_camera: 'Máy ảnh',
  more_details_images_from_sdcard: 'Thẻ nhớ',
  more_details_prompt_login_save_changes: 'Xin hãy đăng nhập trước khi thay đổi thông tin',
  more_details_prompt_login_add_new_place: 'Xin hãy đăng nhập trước khi thêm nơi mới',
  more_details_images_are_loading: 'Xin hãy chờ cho việc tải ảnh hoàn tất',
  more_details_at_least_one_image_added: 'Phải có ít nhất một ảnh cho nơi này',
  more_details_input_error_detected: 'Một vài thông tin bị nhập sai',
  more_details_no_images_selected: 'Không thể chọn những ảnh này',
  more_details_delete_place_confirm_title: 'Xác nhận',
  more_details_delete_place_confirm_message: 'Bạn có chắc muốn xóa nơi này?',
  more_details_delete_place_error_message: 'Không thể xóa nơi này được',
  more_details_delete_place_alert_yes_button: 'Có',
  more_details_delete_place_alert_no_button: 'Không',
  my_added_places_edit_place_title: 'Sửa thông tin',
  my_added_places_place_details_title: 'Thông tin chi tiết',
  my_added_places_not_log_in_message: 'Bạn chưa đăng nhập',
  my_added_places_prompt_log_in: 'Xin hãy đăng nhập trước khi dùng chức năng này',
  place_details_report_error_title: 'Báo cáo sai sót',
  place_details_report_error_content: 'Cho chúng tôi biết nếu bạn phát hiện sai sót',
  place_details_unable_open_map_message: 'Không thể mở ứng dụng bản đồ',
  places_list_navigate_to_add_place_title: 'Thêm nơi mới',
  places_list_search_bar_place_holder: 'Nhập tên nơi cần tìm...',
  input_validation_util_name: 'Tên quán',
  input_validation_util_description: 'Mô tả',
};
